const characters = {
	shenxushao: ["male", "shen", 4, ["shenpingjian"], ["qun", "boss", "bossallowed"], "qun"],
	oldwu_zhugeliang: ["male", "shu", "4/7", ["dcjincui", "olddcqingshi", "olddczhizhe"], ["character:wu_zhugeliang", "die_audio:wu_zhugeliang"]],
	shiguanning: ["male", "qun", "3/7", ["shidunshi"]],
	acetaffy: ["female", "shen", 3, ["taffybaomi", "taffyfeizhu", "taffyzuoai", "taffychusheng"], ["qun"]],
	minitaffy: ["female", "qun", 1, ["taffytangshi", "taffyzisha"]],
	shixushao: ["male", "qun", 4, ["shipingjian"]],
	spshenxushao: ["male", "shen", 1, ["spshenpingjian"], ["qun"]],
	oldtw_niufudongxie: ["double", "qun", 4, ["oldtwjuntun", "oldtwxiongxi", "oldtwxiafeng"], ["character:tw_niufudongxie", "die_audio:tw_niufudongxie"]],
	oldtw_zhangmancheng: ["male", "qun", 4, ["twfengji", "twyiju", "oldtwbudao"], ["character:tw_zhangmancheng", "die_audio:zhangmancheng"]],
	shenyuji: ["male", "shen", 3, ["shenguhuo"]],
	junko: ["female", "shen", 3, ["junkochunhua", "junkokuangqi", "junkowuming"]],
	huiwansunquan: ["male", "wu", 4, ["rezhiheng", "rejiuyuan", "huiwan"]],
	huiwansunquanplus: ["male", "wu", 4, ["rezhiheng", "rejiuyuan", "huiwanplus"]],
	taffyboss_lvbu1: ["male", "shen", 8, ["mashu", "wushuang", "taffyboss_baonu", "taffyboss_jingjia", "boss_aozhan"], ["qun"], "wei"],
	shoushen_caocao: ["male", "shen", 3, ["guixin", "feiying"], ["wei", "character:shen_caocao", "die_audio:shen_caocao"]],
	taffybaby_shen_simayi: ["male", "shen", 3, ["babyrenjie", "babyjilue", "babylianpo"], []],
	shenduyu: ["male", "shen", 5, ["shenmiewu"]],
	shenchengui: ["male", "shen", 3, ["shendcyingtu", "shendccongshi"]],
	oldruiji: ["female", "wu", 3, ["oldqiaoli", "oldqingliang"], ["character:ruiji", "die_audio:ruiji"]],
	oldtengfanglan: ["female", "wu", 3, ["oldluochong", "oldaichen"], ["character:tengfanglan", "die_audio:tengfanglan"]],
	oldol_feiyi: ["male", "shu", 3, ["oldyanru", "oldhezhong"], ["character:ol_feiyi", "die_audio:ol_feiyi"]],
	shenshiguanning: ["male", "shen", "3/7", ["shenshidunshi"]],
	taffyre_xushao: ["male", "qun", 3, ["taffyre_pingjian"]],
	taffyold_sb_caopi: ["male", "wei", 3, ["taffyold_sbxingshang", "taffyold_sbfangzhu", "taffyold_sbsongwei"], ["zhu", "character:sb_caopi", "die_audio:sb_caopi"]],
	taffyold_yuantanyuanshang: ["male", "qun", 4, ["taffyold_neifa"], ["character:yuantanyuanshang", "die_audio:yuantanyuanshang"]],
	taffyold_zhanghua: ["male", "jin", 3, ["olbihun", "olchuanwu", "oljianhe"], ["character:zhanghua", "die_audio:zhanghua"]],
	taffyold_ol_pengyang: ["male", "shu", 3, ["taffyold_olqifan", "taffyold_oltuishi", "nzry_cunmu"], ["character:ol_pengyang", "die_audio:ol_pengyang"]],
	taffyold_sb_sp_zhugeliang: ["male", "shu", 3, ["taffyold_sbhuoji", "taffyold_sbkanpo"], ["character:sb_sp_zhugeliang", "die_audio:sb_sp_zhugeliang"]],
	taffyold_sb_zhugeliang: ["male", "shu", 3, ["taffyold_sbguanxing", "taffyold_sbkongcheng"], ["character:sb_zhugeliang", "die_audio:sb_zhugeliang"]],
	taffyold_sb_guanyu: ["male", "shu", 4, ["taffyold_sbwusheng", "sbyijue"], ["character:sb_guanyu", "die_audio:sb_guanyu"]],
	taffyold_bailingyun: ["female", "wei", 3, ["taffyold_dclinghui", "dcxiace", "dcyuxin"], ["character:bailingyun", "die_audio:bailingyun"]],
	taffyold_clan_zhonghui: ["male", "wei", "3/4", ["taffyold_clanyuzhi", "taffyold_clanxieshu", "taffyold_clanbaozu"], ["clan:颍川钟氏", "character:clan_zhonghui", "die_audio:clan_zhonghui"]],
	taffyold_ol_luyusheng: ["female", "wu", 3, ["taffyold_olcangxin", "olrunwei"], ["character:ol_luyusheng", "die_audio:ol_luyusheng"]],
	taffyold_shen_lusu: ["male", "shen", 3, ["taffyold_tamo", "taffyold_dingzhou", "taffyold_zhimeng"], ["wu", "character:shen_lusu", "die_audio:shen_lusu"]],
	taffyold_wu_guanyu: ["male", "shu", 4, ["taffyold_dcjuewu", "taffyold_dcwuyou", "taffyold_dcyixian"], ["character:wu_guanyu", "die_audio:wu_guanyu"]],
	taffyold_dc_shen_huatuo: ["male", "shen", 3, ["taffyold_jingyu", "taffyold_lvxin", "huandao"], ["qun", "character:dc_shen_huatuo", "die_audio:dc_shen_huatuo"]],
	taffyold_shen_xuzhu: ["male", "shen", 5, ["taffyold_zhengqing", "zhuangpo"], ["wei", "character:shen_xuzhu", "die_audio:shen_xuzhu"]],
	taffyshen_xushao: ["male", "shen", 3, ["taffyshen_pingjian"], ["qun"]],
	aruijier: ["female", "shen", "", [], ["unseen"]],
};

export default characters;
