const characterReplaces = {
	wu_zhugeliang: ["wu_zhugeliang", "taffyold_wu_zhugeliang"],
	guanning: ["guanning", "taffydc_guanning"],
	xushao: ["xushao", "jsrg_xushao", "taffydc_xushao", "taffyre_xushao"],
	niufudongxie: ["tw_niufudongxie", "taffyold_tw_niufudongxie"],
	zhangmancheng: ["dc_zhangmancheng", "tw_zhangmancheng", "taffyold_tw_zhangmancheng", "taffyold_dc_zhangmancheng"],
	sunquan: ["sunquan", "re_sunquan", "sb_sunquan", "dc_sunquan", "xin_sunquan", "jd_sb_sunquan", "ty_sunquan", "taffyhuiwan_sunquan", "taffyhuiwanplus_sunquan"],
	shen_caocao: ["shen_caocao", "old_caocao", "taffymb_shen_caocao"],
	shen_simayi: ["shen_simayi", "xin_simayi", "new_simayi", "taffybaby_shen_simayi", "taffyold_xin_simayi", "taffyold_new_simayi"],
	ruiji: ["ruiji", "dc_ruiji", "taffyold_ruiji"],
	tengfanglan: ["tengfanglan", "dc_tengfanglan", "taffyold_tengfanglan"],
	feiyi: ["ol_feiyi", "feiyi", "tw_feiyi", "taffyold_ol_feiyi"],
	caopi: ["caopi", "re_caopi", "ps_caopi", "sb_caopi", "taffyold_sb_caopi"],
	yuantanyuanshang: ["yuantanyuanshang", "yuantanyuanxiyuanshang", "taffyold_yuantanyuanshang"],
	zhanghua: ["zhanghua", "taffyold_zhanghua"],
	ol_pengyang: ["ol_pengyang", "sp_pengyang", "std_pengyang", "taffyold_ol_pengyang"],
	sp_zhugeliang: ["sp_zhugeliang", "ol_sp_zhugeliang", "re_sp_zhugeliang", "sb_sp_zhugeliang", "jd_sb_sp_zhugeliang", "taffyold_sb_sp_zhugeliang"],
	zhugeliang: ["zhugeliang", "re_zhugeliang", "ps2066_zhugeliang", "ps_zhugeliang", "huan_zhugeliang", "jsrg_zhugeliang", "taffyold_sb_zhugeliang"],
	guanyu: ["guanyu", "re_guanyu", "ol_sb_guanyu", "sb_guanyu", "ps_guanyu", "old_guanyu", "junk_guanyu", "wuhujiang", "jx_guanyu", "jd_sb_guanyu", "ty_guanyu", "xia_guanyu", "drag_guanyu", "taffyold_sb_guanyu", "taffyold_ol_sb_guanyu"],
	bailingyun: ["bailingyun", "taffyold_bailingyun"],
	zhonghui: ["zhonghui", "xin_zhonghui", "re_zhonghui", "old_zhonghui", "pe_zhonghui", "clan_zhonghui", "yj_zhonghui", "std_zhonghui", "taffyold_clan_zhonghui"],
	ol_luyusheng: ["ol_luyusheng", "luyusheng", "taffyold_ol_luyusheng"],
	shen_lusu: ["shen_lusu", "taffyold_shen_lusu"],
	wu_guanyu: ["wu_guanyu", "taffyold_wu_guanyu"],
	shen_huatuo: ["dc_shen_huatuo", "shen_huatuo", "taffyold_dc_shen_huatuo"],
	shen_xuzhu: ["shen_xuzhu", "taffyold_shen_xuzhu"],
	tenggongzhu: ["tenggongzhu", "taffyold_tenggongzhu"],
	hoshino: ["hoshino", "swimsuit_hoshino"],
	baoxin: ["tw_baoxin", "baoxin", "taffyold_tw_baoxin"],
	shichangshi: ["shichangshi", "taffyold_shichangshi"],
	xuyou: ["xuyou", "sp_xuyou", "jsrg_xuyou", "yj_xuyou", "junk_xuyou", "taffyre_xuyou"],
	zhangzhongjing: ["zhangzhongjing", "taffyold_zhangzhongjing"],
	huanggai: ["huanggai", "re_huanggai", "sb_huanggai", "taffyold_sb_huanggai"],
	shen_sunce: ["shen_sunce", "taffyold_shen_sunce"],
	huangzhong: ["re_huangzhong", "ol_huangzhong", "sb_huangzhong", "huangzhong", "jsrg_huangzhong", "yj_huangzhong", "wuhujiang", "taffyold_sb_huangzhong"],
	shen_huangzhong: ["shen_huangzhong", "taffyold_shen_huangzhong"],
	yuechen: ["yuechen", "taffyold_yuechen"],
	ruanyu: ["ruanyu", "taffyold_ruanyu"],
	zhangrang: ["zhangrang", "ol_zhangrang", "junk_zhangrang", "taffyold_zhangrang"],
	hujinding: ["dc_hujinding", "ol_hujinding", "hujinding", "taffyold_ol_hujinding"],
	zhaoyǎn: ["zhaoyǎn", "dc_zhaoyǎn", "taffyold_dc_zhaoyǎn"],
	lukai: ["ol_lukai", "lukai", "taffyold_lukai"],
	liuli: ["dc_liuli", "taffyold_dc_liuli"],
	miheng: ["yue_miheng", "re_miheng", "miheng", "taffyold_yue_miheng"],
	fuqian: ["fuqian", "taffyold_fuqian"],
	guozhao: ["guozhao", "xin_guozhao", "jsrg_guozhao", "taffyold_xin_guozhao"],
	wenyang: ["wenyang", "db_wenyang", "diy_wenyang", "std_db_wenyang", "taffyold_db_wenyang"],
	shen_caopi: ["shen_caopi", "taffyold_shen_caopi"],
	clan_xuncai: ["clan_xuncai", "taffyold_clan_xuncai"],
	shen_xunyu: ["shen_xunyu", "taffyold_shen_xunyu"],
};

export default characterReplaces;
