const characters = {
	taffyboss_xushao: ["male", "shen", 4, ["taffyboss_pingjian"], ["qun", "boss", "bossallowed"], "qun"],
	taffyold_wu_zhugeliang: ["male", "shu", "4/7", ["dcjincui", "taffyold_dcqingshi", "taffyold_dczhizhe"], ["character:wu_zhugeliang", "die:wu_zhugeliang"]],
	taffydc_guanning: ["male", "qun", "3/7", ["taffydc_dunshi"]],
	acetaffy: ["female", "shen", 3, ["taffybaomi", "taffyfeizhu", "taffyzuoai", "taffychusheng"], ["qun"]],
	minitaffy: ["female", "qun", 1, ["taffytangshi", "taffyzisha"]],
	taffydc_xushao: ["male", "qun", 4, ["taffydc_pingjian"]],
	taffyhuiwan_xushao: ["male", "shen", 1, ["taffyhuiwan_pingjian"], ["qun"]],
	taffyold_tw_niufudongxie: ["double", "qun", 4, ["taffyold_twjuntun", "taffyold_twxiongxi", "taffyold_twxiafeng"], ["character:tw_niufudongxie", "die:tw_niufudongxie"]],
	taffyold_tw_zhangmancheng: ["male", "qun", 4, ["twfengji", "twyiju", "taffyold_twbudao"], ["character:tw_zhangmancheng", "die:zhangmancheng"]],
	taffyshen_yuji: ["male", "shen", 3, ["taffyshen_guhuo"]],
	junko: ["female", "shen", 3, ["junkochunhua", "junkokuangqi", "junkowuming"]],
	taffyhuiwan_sunquan: ["male", "wu", 4, ["rezhiheng", "rejiuyuan", "huiwan"]],
	taffyhuiwanplus_sunquan: ["male", "wu", 4, ["rezhiheng", "rejiuyuan", "huiwanplus"]],
	taffyboss_lvbu1: ["male", "shen", 8, ["mashu", "wushuang", "taffyboss_baonu", "taffyboss_jingjia", "boss_aozhan"], ["qun"], "wei"],
	taffymb_shen_caocao: ["male", "shen", 3, ["guixin", "feiying"], ["wei", "character:shen_caocao", "die:shen_caocao"]],
	taffybaby_shen_simayi: ["male", "shen", 3, ["taffybaby_renjie", "taffybaby_jilue", "taffybaby_lianpo"], []],
	taffyshen_duyu: ["male", "shen", 5, ["taffyshen_miewu"]],
	taffyshen_chengui: ["male", "shen", 3, ["taffyshen_dcyingtu", "taffyshen_dccongshi"]],
	taffyold_ruiji: ["female", "wu", 3, ["taffyold_qiaoli", "taffyold_qingliang"], ["character:ruiji", "die:ruiji"]],
	taffyold_tengfanglan: ["female", "wu", 3, ["taffyold_luochong", "taffyold_aichen"], ["character:tengfanglan", "die:tengfanglan"]],
	taffyold_ol_feiyi: ["male", "shu", 3, ["taffyold_yanru", "taffyold_hezhong"], ["character:ol_feiyi", "die:ol_feiyi"]],
	taffyshendc_guanning: ["male", "shen", "3/7", ["taffyshendc_dunshi"]],
	taffyre_xushao: ["male", "qun", 3, ["taffyre_pingjian"]],
	taffyold_sb_caopi: ["male", "wei", 3, ["taffyold_sbxingshang", "taffyold_sbfangzhu", "taffyold_sbsongwei"], ["zhu", "character:sb_caopi", "die:sb_caopi"]],
	taffyold_yuantanyuanshang: ["male", "qun", 4, ["taffyold_neifa"], ["character:yuantanyuanshang", "die:yuantanyuanshang"]],
	taffyold_zhanghua: ["male", "jin", 3, ["olbihun", "olchuanwu", "oljianhe"], ["character:zhanghua", "die:zhanghua"]],
	taffyold_ol_pengyang: ["male", "shu", 3, ["taffyold_olxiaofan", "taffyold_oltuishi", "nzry_cunmu"], ["tempname:ol_pengyang", "character:ol_pengyang", "die:ol_pengyang"]],
	taffyold_sb_sp_zhugeliang: ["male", "shu", 3, ["taffyold_sbhuoji", "taffyold_sbkanpo"], ["character:sb_sp_zhugeliang", "die:sb_sp_zhugeliang"]],
	taffyold_sb_zhugeliang: ["male", "shu", 3, ["taffyold_sbguanxing", "taffyold_sbkongcheng"], ["character:sb_zhugeliang", "die:sb_zhugeliang"]],
	taffyold_sb_guanyu: ["male", "shu", 4, ["taffyold_sbwusheng", "taffyold_sbyijue"], ["character:sb_guanyu", "die:sb_guanyu"]],
	taffyold_bailingyun: ["female", "wei", 3, ["taffyold_dclinghui", "dcxiace", "dcyuxin"], ["character:bailingyun", "die:bailingyun"]],
	taffyold_clan_zhonghui: ["male", "wei", "3/4", ["taffyold_clanyuzhi", "taffyold_clanxieshu", "taffyold_clanbaozu"], ["clan:颍川钟氏", "character:clan_zhonghui", "die:clan_zhonghui"]],
	taffyold_ol_luyusheng: ["female", "wu", 3, ["taffyold_olcangxin", "olrunwei"], ["character:ol_luyusheng", "die:ol_luyusheng"]],
	taffyold_shen_lusu: ["male", "shen", 3, ["taffyold_tamo", "taffyold_dingzhou", "taffyold_zhimeng"], ["wu", "character:shen_lusu", "die:shen_lusu"]],
	taffyold_wu_guanyu: ["male", "shu", 4, ["taffyold_dcjuewu", "taffyold_dcwuyou", "taffyold_dcyixian"], ["character:wu_guanyu", "die:wu_guanyu"]],
	taffyold_dc_shen_huatuo: ["male", "shen", 3, ["taffyold_jingyu", "taffyold_lvxin", "huandao"], ["qun", "character:dc_shen_huatuo", "die:dc_shen_huatuo"]],
	taffyold_shen_xuzhu: ["male", "shen", 5, ["taffyold_zhengqing", "zhuangpo"], ["wei", "character:shen_xuzhu", "die:shen_xuzhu"]],
	taffyshen_xushao: ["male", "shen", 3, ["taffyshen_pingjian"], ["qun"]],
	taffyold_tenggongzhu: ["female", "wu", 4, ["taffyold_xingchong", "taffyold_liunian"], ["character:tenggongzhu", "die:tenggongzhu"]],
	hoshino: ["female", "shen", 4, ["hoshino_zhenya", "hoshino_jijiu", "hoshino_huizhang", "hoshino_shushou"], ["unseen"]],
	swimsuit_hoshino: ["female", "shen", 3, ["hoshino_shuiyuan", "hoshino_shuiji", "hoshino_naishu", "hoshino_haile"]],
	limulu: ["male", "shen", 3, ["limulu_baoshi", "limulu_zhihui", "limulu_mowang"]],
	taffyold_tw_baoxin: ["male", "qun", 4, ["taffyold_twmutao", "twyimou"], ["character:tw_baoxin", "die:tw_baoxin"]],
	aruijier: ["female", "shen", "", [], ["unseen"]],
};

export default characters;
