const characterReplaces = {
	wu_zhugeliang: ["wu_zhugeliang", "taffyold_wu_zhugeliang"],
	guanning: ["guanning", "taffydc_guanning"],
	xushao: ["xushao", "jsrg_xushao", "taffydc_xushao", "taffyre_xushao"],
	niufudongxie: ["tw_niufudongxie", "taffyold_tw_niufudongxie"],
	zhangmancheng: ["dc_zhangmancheng", "tw_zhangmancheng", "taffyold_tw_zhangmancheng", "taffyold_dc_zhangmancheng"],
	sunquan: ["sunquan", "re_sunquan", "sb_sunquan", "dc_sunquan", "taffyhuiwan_sunquan", "taffyhuiwanplus_sunquan"],
	shen_caocao: ["shen_caocao", "taffymb_shen_caocao"],
	shen_simayi: ["shen_simayi", "taffybaby_shen_simayi"],
	ruiji: ["ruiji", "dc_ruiji", "taffyold_ruiji"],
	tengfanglan: ["tengfanglan", "dc_tengfanglan", "taffyold_tengfanglan"],
	feiyi: ["ol_feiyi", "feiyi", "tw_feiyi", "taffyold_ol_feiyi"],
	caopi: ["caopi", "re_caopi", "ps_caopi", "sb_caopi", "taffyold_sb_caopi"],
	yuantanyuanshang: ["yuantanyuanshang", "yuantanyuanxiyuanshang", "taffyold_yuantanyuanshang"],
	zhanghua: ["zhanghua", "taffyold_zhanghua"],
	ol_pengyang: ["ol_pengyang", "sp_pengyang", "taffyold_ol_pengyang"],
	sp_zhugeliang: ["sp_zhugeliang", "ol_sp_zhugeliang", "re_sp_zhugeliang", "sb_sp_zhugeliang", "taffyold_sb_sp_zhugeliang"],
	zhugeliang: ["zhugeliang", "re_zhugeliang", "sb_zhugeliang", "jsrg_zhugeliang", "ps2066_zhugeliang", "ps_zhugeliang", "taffyold_sb_zhugeliang"],
	guanyu: ["guanyu", "re_guanyu", "ps_guanyu", "old_guanyu", "sb_guanyu", "taffyold_sb_guanyu"],
	bailingyun: ["bailingyun", "taffyold_bailingyun"],
	clan_zhonghui: ["clan_zhonghui", "taffyold_clan_zhonghui"],
	ol_luyusheng: ["ol_luyusheng", "luyusheng", "taffyold_ol_luyusheng"],
	shen_lusu: ["shen_lusu", "taffyold_shen_lusu"],
	wu_guanyu: ["wu_guanyu", "taffyold_wu_guanyu"],
	shen_huatuo: ["dc_shen_huatuo", "shen_huatuo", "taffyold_dc_shen_huatuo"],
	shen_xuzhu: ["shen_xuzhu", "taffyold_shen_xuzhu"],
	tenggongzhu: ["tenggongzhu", "taffyold_tenggongzhu"],
	hoshino: ["hoshino", "swimsuit_hoshino"],
	baoxin: ["tw_baoxin", "baoxin", "taffyold_tw_baoxin"],
	shichangshi: ["shichangshi", "taffyold_shichangshi"],
};

export default characterReplaces;
